version: '2'
services:
  redis:
    image: redis:4.0.12
    container_name: redis
    command: redis-server
    ports:
      - 6379:6379
#    network_mode: "common"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 5000:5000
      - 9102:9102
    links:
      - "redis:redis"
#    network_mode: "common"
networks:
  common: